=== mentebinaria/readpe/lib/libmxml/doc/mxmldoc.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Mini-XML 2.7 documentation schema for mxmldoc output.
      Copyright 2003-2011 by Michael Sweet.

      This program is free software; you can redistribute it and/or
      modify it under the terms of the GNU Library General Public
      License as published by the Free Software Foundation; either
      version 2, or (at your option) any later version.

      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.
    </xsd:documentation>
  </xsd:annotation>

  <!-- basic element definitions -->
  <xsd:element name="argument" type="argumentType"/>
  <xsd:element name="class" type="classType"/>
  <xsd:element name="constant" type="constantType"/>
  <xsd:element name="description" type="xsd:string"/>
  <xsd:element name="enumeration" type="enumerationType"/>
  <xsd:element name="function" type="functionType"/>
  <xsd:element name="mxmldoc" type="mxmldocType"/>
  <xsd:element name="namespace" type="namespaceType"/>
  <xsd:element name="returnvalue" type="returnvalueType"/>
  <xsd:element name="seealso" type="identifierList"/>
  <xsd:element name="struct" type="structType"/>
  <xsd:element name="typedef" type="typedefType"/>
  <xsd:element name="type" type="xsd:string"/>
  <xsd:element name="union" type="unionType"/>
  <xsd:element name="variable" type="variableType"/>

  <!-- descriptions of complex elements -->
  <xsd:complexType name="argumentType">
    <xsd:sequence>
      <xsd:element ref="type" minOccurs="1" maxOccurs="1"/>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="default" type="xsd:string" use="optional"/>
    <xsd:attribute name="name" type="identifier" use="required"/>
    <xsd:attribute name="direction" type="direction" use="optional" default="I"/>
  </xsd:complexType>

  <xsd:complexType name="classType">
    <xsd:sequence>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
	<xsd:element ref="class"/>
	<xsd:element ref="enumeration"/>
	<xsd:element ref="function"/>
	<xsd:element ref="struct"/>
	<xsd:element ref="typedef"/>
	<xsd:element ref="union"/>
	<xsd:element ref="variable"/>
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="name" type="identifier" use="required"/>
    <xsd:attribute name="parent" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="constantType">
    <xsd:sequence>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="identifier" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="enumerationType">
    <xsd:sequence>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
      <xsd:element ref="constant" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="identifier" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="functionType">
    <xsd:sequence>
      <xsd:element ref="returnvalue" minOccurs="0" maxOccurs="1"/>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
      <xsd:element ref="argument" minOccurs="1" maxOccurs="unbounded"/>
      <xsd:element ref="seealso" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="identifier" use="required"/>
    <xsd:attribute name="scope" type="scope" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="mxmldocType">
    <xsd:choice minOccurs="0" maxOccurs="unbounded">
      <xsd:element ref="class"/>
      <xsd:element ref="enumeration"/>
      <xsd:element ref="function"/>
      <xsd:element ref="namespace"/>
      <xsd:element ref="struct"/>
      <xsd:element ref="typedef"/>
      <xsd:element ref="union"/>
      <xsd:element ref="variable"/>
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="namespaceType">
    <xsd:sequence>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
	<xsd:element ref="class"/>
	<xsd:element ref="enumeration"/>
	<xsd:element ref="function"/>
	<xsd:element ref="struct"/>
	<xsd:element ref="typedef"/>
	<xsd:element ref="union"/>
	<xsd:element ref="variable"/>
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="name" type="identifier" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="returnvalueType">
    <xsd:sequence>
      <xsd:element ref="type" minOccurs="1" maxOccurs="1"/>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="structType">
    <xsd:sequence>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
	<xsd:element ref="variable"/>
	<xsd:element ref="function"/>
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="name" type="identifier" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="typedefType">
    <xsd:sequence>
      <xsd:element ref="type" minOccurs="1" maxOccurs="1"/>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="identifier" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="unionType">
    <xsd:sequence>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
      <xsd:element ref="variable" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="identifier" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="variableType">
    <xsd:sequence>
      <xsd:element ref="type" minOccurs="1" maxOccurs="1"/>
      <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="identifier" use="required"/>
  </xsd:complexType>

  <!-- data types -->
  <xsd:simpleType name="direction">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="I"/>
      <xsd:enumeration value="O"/>
      <xsd:enumeration value="IO"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="identifier">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[a-zA-Z_(.]([a-zA-Z_(.,)* 0-9])*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="identifierList">
    <xsd:list itemType="identifier"/>
  </xsd:simpleType>

  <xsd:simpleType name="scope">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value=""/>
      <xsd:enumeration value="private"/>
      <xsd:enumeration value="protected"/>
      <xsd:enumeration value="public"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== mentebinaria/readpe/lib/libmxml/mxml.xml
<?xml version="1.0" encoding="utf-8"?>
<mxmldoc xmlns="http://www.easysw.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.minixml.org/mxmldoc.xsd">
  <function name="mxmlAdd">
    <description>Add a node to a tree.

Adds the specified node to the parent. If the child argument is not
NULL, puts the new node before or after the specified child depending
on the value of the where argument. If the child argument is NULL,
puts the new node at the beginning of the child list (MXML_ADD_BEFORE)
or at the end of the child list (MXML_ADD_AFTER). The constant
MXML_ADD_TO_PARENT can be used to specify a NULL child pointer.</description>
    <argument name="parent" direction="I">
      <type>mxml_node_t *</type>
      <description>Parent node</description>
    </argument>
    <argument name="where" direction="I">
      <type>int</type>
      <description>Where to add, MXML_ADD_BEFORE or MXML_ADD_AFTER</description>
    </argument>
    <argument name="child" direction="I">
      <type>mxml_node_t *</type>
      <description>Child node for where or MXML_ADD_TO_PARENT</description>
    </argument>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Node to add</description>
    </argument>
  </function>
  <function name="mxmlDelete">
    <description>Delete a node and all of its children.

If the specified node has a parent, this function first removes the
node from its parent using the mxmlRemove() function.</description>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Node to delete</description>
    </argument>
  </function>
  <function name="mxmlElementDeleteAttr">
    <description>Delete an attribute.

@since Mini-XML 2.4@</description>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Element</description>
    </argument>
    <argument name="name" direction="I">
      <type>const char *</type>
      <description>Attribute name</description>
    </argument>
  </function>
  <function name="mxmlElementGetAttr">
    <returnvalue>
      <type>const char *</type>
      <description>Attribute value or NULL</description>
    </returnvalue>
    <description>Get an attribute.

This function returns NULL if the node is not an element or the
named attribute does not exist.</description>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Element node</description>
    </argument>
    <argument name="name" direction="I">
      <type>const char *</type>
      <description>Name of attribute</description>
    </argument>
  </function>
  <function name="mxmlElementSetAttr">
    <description>Set an attribute.

If the named attribute already exists, the value of the attribute
is replaced by the new string value. The string value is copied
into the element node. This function does nothing if the node is
not an element.</description>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Element node</description>
    </argument>
    <argument name="name" direction="I">
      <type>const char *</type>
      <description>Name of attribute</description>
    </argument>
    <argument name="value" direction="I">
      <type>const char *</type>
      <description>Attribute value</description>
    </argument>
  </function>
  <function name="mxmlElementSetAttrf">
    <description>Set an attribute with a formatted value.

If the named attribute already exists, the value of the attribute
is replaced by the new formatted string. The formatted string value is
copied into the element node. This function does nothing if the node
is not an element.

@since Mini-XML 2.3@</description>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Element node</description>
    </argument>
    <argument name="name" direction="I">
      <type>const char *</type>
      <description>Name of attribute</description>
    </argument>
    <argument name="format" direction="I">
      <type>const char *</type>
      <description>Printf-style attribute value</description>
    </argument>
    <argument name="..." direction="I">
      <type />      <description>Additional arguments as needed</description>
    </argument>
  </function>
  <function name="mxmlEntityAddCallback">
    <returnvalue>
      <type>int</type>
      <description>0 on success, -1 on failure</description>
    </returnvalue>
    <description>Add a callback to convert entities to Unicode.</description>
    <argument name="cb" direction="I">
      <type>mxml_entity_cb_t</type>
      <description>Callback function to add</description>
    </argument>
  </function>
  <function name="mxmlEntityGetName">
    <returnvalue>
      <type>const char *</type>
      <description>Entity name or NULL</description>
    </returnvalue>
    <description>Get the name that corresponds to the character value.

If val does not need to be represented by a named entity, NULL is returned.</description>
    <argument name="val" direction="I">
      <type>int</type>
      <description>Character value</description>
    </argument>
  </function>
  <function name="mxmlEntityGetValue">
    <returnvalue>
      <type>int</type>
      <description>Character value or -1 on error</description>
    </returnvalue>
    <description>Get the character corresponding to a named entity.

The entity name can also be a numeric constant. -1 is returned if the
name is not known.</description>
    <argument name="name" direction="I">
      <type>const char *</type>
      <description>Entity name</description>
    </argument>
  </function>
  <function name="mxmlEntityRemoveCallback">
    <description>Remove a callback.</description>
    <argument name="cb" direction="I">
      <type>mxml_entity_cb_t</type>
      <description>Callback function to remove</description>
    </argument>
  </function>
  <function name="mxmlFindElement">
    <returnvalue>
      <type>mxml_node_t *</type>
      <description>Element node or NULL</description>
    </returnvalue>
    <description>Find the named element.

The search is constrained by the name, attribute name, and value; any
NULL names or values are treated as wildcards, so different kinds of
searches can be implemented by looking for all elements of a given name
or all elements with a specific attribute. The descend argument determines
whether the search descends into child nodes; normally you will use
MXML_DESCEND_FIRST for the initial search and MXML_NO_DESCEND to find
additional direct descendents of the node. The top node argument
constrains the search to a particular node's children.</description>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Current node</description>
    </argument>
    <argument name="top" direction="I">
      <type>mxml_node_t *</type>
      <description>Top node</description>
    </argument>
    <argument name="name" direction="I">
      <type>const char *</type>
      <description>Element name or NULL for any</description>
    </argument>
    <argument name="attr" direction="I">
      <type>const char *</type>
      <description>Attribute name, or NULL for none</description>
    </argument>
    <argument name="value" direction="I">
      <type>const char *</type>
      <description>Attribute value, or NULL for any</description>
    </argument>
    <argument name="descend" direction="I">
      <type>int</type>
      <description>Descend into tree - MXML_DESCEND, MXML_NO_DESCEND, or MXML_DESCEND_FIRST</description>
    </argument>
  </function>
  <function name="mxmlFindPath">
    <returnvalue>
      <type>mxml_node_t *</type>
      <description>Found node or NULL</description>
    </returnvalue>
    <description>Find a node with the given path.

The &quot;path&quot; is a slash-separated list of element names. The name &quot;*&quot; is
considered a wildcard for one or more levels of elements.  For example,
&quot;foo/one/two&quot;, &quot;bar/two/one&quot;, &quot;*/one&quot;, and so forth.

The first child node of the found node is returned if the given node has
children and the first child is a value node.

@since Mini-XML 2.7@</description>
    <argument name="top" direction="I">
      <type>mxml_node_t *</type>
      <description>Top node</description>
    </argument>
    <argument name="path" direction="I">
      <type>const char *</type>
      <description>Path to element</description>
    </argument>
  </function>
  <function name="mxmlGetCDATA">
    <returnvalue>
      <type>const char *</type>
      <description>CDATA value or NULL</description>
    </returnvalue>
    <description>Get the value for a CDATA node.

@code NULL@ is returned if the node is not a CDATA element.

@since Mini-XML 2.7@</description>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Node to get</description>
    </argument>
  </function>
  <function name="mxmlGetCustom">
    <returnvalue>
      <type>const void *</type>
      <description>Custom value or NULL</description>
    </returnvalue>
    <description>Get the value for a custom node.

@code NULL@ is returned if the node (or its first child) is not a custom
value node.

@since Mini-XML 2.7@</description>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Node to get</description>
    </argument>
  </function>
  <function name="mxmlGetElement">
    <returnvalue>
      <type>const char *</type>
      <description>Element name or NULL</description>
    </returnvalue>
    <description>Get the name for an element node.

@code NULL@ is returned if the node is not an element node.

@since Mini-XML 2.7@</description>
    <argument name="node" direction="I">
      <type>mxml_node_t *</type>
      <description>Node to get</description>
    </argument>
  </function>
  <function name="mxmlGetFirstChild">
    <returnvalue>
      <type>mxml_node_t *</type>
